from twisted.python.compat import unicode as unicode
from twisted.words.xish import domish as domish
from typing import Any, Optional

NS_XML: str
NS_XMPP_STREAMS: str
NS_XMPP_STANZAS: str
STANZA_CONDITIONS: Any
CODES_TO_CONDITIONS: Any

class BaseError(Exception):
    namespace: Any = ...
    condition: Any = ...
    text: Any = ...
    textLang: Any = ...
    appCondition: Any = ...
    def __init__(self, condition: Any, text: Optional[Any] = ..., textLang: Optional[Any] = ..., appCondition: Optional[Any] = ...) -> None: ...
    def getElement(self): ...

class StreamError(BaseError):
    namespace: Any = ...
    def getElement(self): ...

class StanzaError(BaseError):
    namespace: Any = ...
    type: Any = ...
    code: Any = ...
    children: Any = ...
    iq: Any = ...
    def __init__(self, condition: Any, type: Optional[Any] = ..., text: Optional[Any] = ..., textLang: Optional[Any] = ..., appCondition: Optional[Any] = ...) -> None: ...
    def getElement(self): ...
    def toResponse(self, stanza: Any): ...

def exceptionFromStreamError(element: Any): ...
def exceptionFromStanza(stanza: Any): ...
