from typing import Any
from zope.interface import Interface

class IInitializer(Interface): ...

class IInitiatingInitializer(IInitializer):
    xmlstream: Any = ...
    def initialize() -> None: ...

class IIQResponseTracker(Interface):
    iqDeferreds: Any = ...

class IXMPPHandler(Interface):
    parent: Any = ...
    xmlstream: Any = ...
    def setHandlerParent(parent: Any) -> None: ...
    def disownHandlerParent(parent: Any) -> None: ...
    def makeConnection(xs: Any) -> None: ...
    def connectionMade() -> None: ...
    def connectionInitialized() -> None: ...
    def connectionLost(reason: Any) -> None: ...

class IXMPPHandlerCollection(Interface):
    def __iter__() -> Any: ...
    def addHandler(handler: Any) -> None: ...
    def removeHandler(handler: Any) -> None: ...

class IService(Interface):
    def componentConnected(xs: Any) -> None: ...
    def componentDisconnected() -> None: ...
    def transportConnected(xs: Any) -> None: ...
