from twisted.words.protocols.jabber.xmpp_stringprep import nameprep as nameprep, nodeprep as nodeprep, resourceprep as resourceprep
from typing import Any, Optional

class InvalidFormat(Exception): ...

def parse(jidstring: Any): ...
def prep(user: Any, host: Any, resource: Any): ...
def internJID(jidstring: Any): ...

class JID:
    user: Any = ...
    host: Any = ...
    resource: Any = ...
    def __init__(self, str: Optional[Any] = ..., tuple: Optional[Any] = ...) -> None: ...
    def userhost(self): ...
    def userhostJID(self): ...
    def full(self): ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> Any: ...
    def __unicode__(self): ...
