from twisted.python.compat import iteritems as iteritems, networkString as networkString
from typing import Any
from zope.interface import Interface

class ISASLMechanism(Interface):
    name: Any = ...
    def getInitialResponse() -> None: ...
    def getResponse(challenge: Any) -> None: ...

class Anonymous:
    name: str = ...
    def getInitialResponse(self) -> None: ...

class Plain:
    name: str = ...
    authzid: Any = ...
    authcid: Any = ...
    password: Any = ...
    def __init__(self, authzid: Any, authcid: Any, password: Any) -> None: ...
    def getInitialResponse(self): ...

class DigestMD5:
    name: str = ...
    username: Any = ...
    password: Any = ...
    defaultRealm: Any = ...
    digest_uri: Any = ...
    def __init__(self, serv_type: Any, host: Any, serv_name: Any, username: Any, password: Any) -> None: ...
    def getInitialResponse(self) -> None: ...
    def getResponse(self, challenge: Any): ...
