from twisted.python.deprecate import deprecatedModuleAttribute as deprecatedModuleAttribute
from typing import Any
from zope.interface import Interface

crippled: bool

class ILookupTable(Interface):
    def lookup(c: Any) -> None: ...

class IMappingTable(Interface):
    def map(c: Any) -> None: ...

class LookupTableFromFunction:
    lookup: Any = ...
    def __init__(self, in_table_function: Any) -> None: ...

class LookupTable:
    def __init__(self, table: Any) -> None: ...
    def lookup(self, c: Any): ...

class MappingTableFromFunction:
    map: Any = ...
    def __init__(self, map_table_function: Any) -> None: ...

class EmptyMappingTable:
    def __init__(self, in_table_function: Any) -> None: ...
    def map(self, c: Any): ...

class Profile:
    mappings: Any = ...
    normalize: Any = ...
    prohibiteds: Any = ...
    do_check_unassigneds: Any = ...
    do_check_bidi: Any = ...
    def __init__(self, mappings: Any = ..., normalize: bool = ..., prohibiteds: Any = ..., check_unassigneds: bool = ..., check_bidi: bool = ...) -> None: ...
    def prepare(self, string: Any): ...
    def map(self, string: Any): ...
    def check_prohibiteds(self, string: Any) -> None: ...
    def check_unassigneds(self, string: Any) -> None: ...
    def check_bidirectionals(self, string: Any) -> None: ...

class NamePrep:
    prohibiteds: Any = ...
    def prepare(self, string: Any): ...
    def check_prohibiteds(self, string: Any) -> None: ...
    def nameprep(self, label: Any): ...

C_11: Any
C_12: Any
C_21: Any
C_22: Any
C_3: Any
C_4: Any
C_5: Any
C_6: Any
C_7: Any
C_8: Any
C_9: Any
B_1: Any
B_2: Any
nodeprep: Any
resourceprep: Any
nameprep: Any
