from twisted.python.deprecate import getWarningMethod as getWarningMethod
from twisted.python.failure import Failure as Failure
from twisted.python.log import err as err
from twisted.python.reflect import qual as qual
from typing import Any

class BaseProcess:
    pid: Any = ...
    status: Any = ...
    lostProcess: int = ...
    proto: Any = ...
    def __init__(self, protocol: Any) -> None: ...
    def processEnded(self, status: Any) -> None: ...
    def maybeCallProcessEnded(self) -> None: ...
