from twisted.internet import abstract as abstract
from twisted.internet.serialport import BaseSerialPort as BaseSerialPort
from typing import Any

class SerialPort(BaseSerialPort, abstract.FileDescriptor):
    connected: int = ...
    reactor: Any = ...
    protocol: Any = ...
    outQueue: Any = ...
    closed: int = ...
    closedNotifies: int = ...
    writeInProgress: int = ...
    def __init__(self, protocol: Any, deviceNameOrPortNumber: Any, reactor: Any, baudrate: int = ..., bytesize: Any = ..., parity: Any = ..., stopbits: Any = ..., xonxoff: int = ..., rtscts: int = ...) -> None: ...
    def serialReadEvent(self) -> None: ...
    def write(self, data: Any) -> None: ...
    def serialWriteEvent(self) -> None: ...
    def connectionLost(self, reason: Any) -> None: ...
