from typing import Any, Optional

class _ConsumerMixin:
    producer: Any = ...
    producerPaused: bool = ...
    streamingProducer: bool = ...
    def startWriting(self) -> None: ...
    def registerProducer(self, producer: Any, streaming: Any) -> None: ...
    def unregisterProducer(self) -> None: ...

class _LogOwner:
    def logPrefix(self): ...

class FileDescriptor(_ConsumerMixin, _LogOwner):
    connected: int = ...
    disconnected: int = ...
    disconnecting: int = ...
    dataBuffer: bytes = ...
    offset: int = ...
    SEND_LIMIT: Any = ...
    reactor: Any = ...
    def __init__(self, reactor: Optional[Any] = ...) -> None: ...
    producer: Any = ...
    def connectionLost(self, reason: Any) -> None: ...
    def writeSomeData(self, data: Any) -> None: ...
    def doRead(self) -> None: ...
    producerPaused: bool = ...
    def doWrite(self): ...
    def writeConnectionLost(self, reason: Any) -> None: ...
    def readConnectionLost(self, reason: Any) -> None: ...
    def write(self, data: Any) -> None: ...
    def writeSequence(self, iovec: Any) -> None: ...
    def loseConnection(self, _connDone: Any = ...) -> None: ...
    def loseWriteConnection(self) -> None: ...
    def stopReading(self) -> None: ...
    def stopWriting(self) -> None: ...
    def startReading(self) -> None: ...
    def startWriting(self) -> None: ...
    bufferSize: Any = ...
    def stopConsuming(self) -> None: ...
    def resumeProducing(self) -> None: ...
    def pauseProducing(self) -> None: ...
    def stopProducing(self) -> None: ...
    def fileno(self): ...

def isIPAddress(addr: Any, family: Any = ...): ...
def isIPv6Address(addr: Any): ...
