from twisted.internet import _glibbase
from typing import Any

class GIReactor(_glibbase.GlibReactorBase):
    INFLAGS: Any = ...
    OUTFLAGS: Any = ...
    def __init__(self, useGtk: bool = ...) -> None: ...
    def registerGApplication(self, app: Any) -> None: ...

class PortableGIReactor(_glibbase.PortableGlibReactorBase):
    def __init__(self, useGtk: bool = ...) -> None: ...
    def registerGApplication(self, app: Any) -> None: ...

def install(useGtk: bool = ...): ...
