from twisted.internet import _glibbase
from typing import Any

class Gtk2Reactor(_glibbase.GlibReactorBase):
    INFLAGS: Any = ...
    OUTFLAGS: Any = ...
    def __init__(self, useGtk: bool = ...) -> None: ...

class PortableGtkReactor(_glibbase.PortableGlibReactorBase):
    def __init__(self, useGtk: bool = ...) -> None: ...

def install(useGtk: bool = ...): ...
install = install
install = portableInstall
