from twisted.internet import posixbase
from typing import Any
from zope.interface import Interface

class _IKQueue(Interface):
    kqueue: Any = ...
    kevent: Any = ...

class KQueueReactor(posixbase.PosixReactorBase):
    def __init__(self, _kqueueImpl: Any = ...) -> None: ...
    def beforeDaemonize(self) -> None: ...
    def afterDaemonize(self) -> None: ...
    def addReader(self, reader: Any) -> None: ...
    def addWriter(self, writer: Any) -> None: ...
    def removeReader(self, reader: Any) -> None: ...
    def removeWriter(self, writer: Any) -> None: ...
    def removeAll(self): ...
    def getReaders(self): ...
    def getWriters(self): ...
    def doKEvent(self, timeout: Any) -> None: ...
    doIteration: Any = ...

def install() -> None: ...
