_cancellations: int
_eventTriggers: Any
_internalReaders: Any
_justStopped: bool
_nameResolver: Any
_newTimedCalls: Any
_pendingTimedCalls: Any
_reads: Any
_started: bool
_startedBefore: bool
_writes: Any
resolver: Any
running: bool
threadCallQueue: Any
usingThreads: bool
waker: Any
