from twisted.internet import posixbase
from typing import Any

class SelectReactor(posixbase.PosixReactorBase, _extraBase):
    def __init__(self) -> None: ...
    def doSelect(self, timeout: Any) -> None: ...
    doIteration: Any = ...
    def addReader(self, reader: Any) -> None: ...
    def addWriter(self, writer: Any) -> None: ...
    def removeReader(self, reader: Any) -> None: ...
    def removeWriter(self, writer: Any) -> None: ...
    def removeAll(self): ...
    def getReaders(self): ...
    def getWriters(self): ...

def install() -> None: ...
