import serial as serial
from serial import EIGHTBITS as EIGHTBITS, FIVEBITS as FIVEBITS, PARITY_EVEN as PARITY_EVEN, PARITY_NONE as PARITY_NONE, PARITY_ODD as PARITY_ODD, SEVENBITS as SEVENBITS, SIXBITS as SIXBITS, STOPBITS_ONE as STOPBITS_ONE, STOPBITS_TWO as STOPBITS_TWO
from twisted.internet._posixserialport import SerialPort as SerialPort
from typing import Any

class BaseSerialPort:
    def setBaudRate(self, baudrate: Any) -> None: ...
    def inWaiting(self): ...
    def flushInput(self) -> None: ...
    def flushOutput(self) -> None: ...
    def sendBreak(self) -> None: ...
    def getDSR(self): ...
    def getCD(self): ...
    def getRI(self): ...
    def getCTS(self): ...
    def setDTR(self, on: int = ...) -> None: ...
    def setRTS(self, on: int = ...) -> None: ...
