from typing import Any

def deferToThreadPool(reactor: Any, threadpool: Any, f: Any, *args: Any, **kwargs: Any): ...
def deferToThread(f: Any, *args: Any, **kwargs: Any): ...
def callMultipleInThread(tupleList: Any) -> None: ...
def blockingCallFromThread(reactor: Any, f: Any, *a: Any, **kw: Any): ...
