from twisted.internet import _threadedselect
from typing import Any
from wxPython.wx import Timer as wxTimer

class ProcessEventsTimer(wxTimer):
    wxapp: Any = ...
    def __init__(self, wxapp: Any) -> None: ...
    def Notify(self) -> None: ...

class WxReactor(_threadedselect.ThreadedSelectReactor):
    wxapp: Any = ...
    def registerWxApp(self, wxapp: Any) -> None: ...
    def stop(self) -> None: ...
    def run(self, installSignalHandlers: bool = ...): ...

def install(): ...
