from twisted.conch.ssh import keys as keys
from twisted.python import failure as failure, filepath as filepath, log as log, usage as usage
from twisted.python.compat import raw_input as raw_input
from typing import Any

supportedKeyTypes: Any

class GeneralOptions(usage.Options):
    synopsis: str = ...
    longdesc: str = ...
    optParameters: Any = ...
    optFlags: Any = ...
    compData: Any = ...

def run() -> None: ...
def enumrepresentation(options: Any): ...
def handleError() -> None: ...
def generateRSAkey(options: Any) -> None: ...
def generateDSAkey(options: Any) -> None: ...
def generateECDSAkey(options: Any) -> None: ...
def printFingerprint(options: Any) -> None: ...
def changePassPhrase(options: Any) -> None: ...
def displayPublicKey(options: Any) -> None: ...
