from twisted.python.util import FancyStrMixin
from typing import Any

class SerialNumber(FancyStrMixin):
    showAttributes: Any = ...
    def __init__(self, number: Any, serialBits: int = ...) -> None: ...
    def __int__(self): ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __add__(self, other: object) -> SerialNumber: ...
    def __hash__(self) -> Any: ...
    @classmethod
    def fromRFC4034DateString(cls, utcDateString: Any): ...
    def toRFC4034DateString(self): ...
