from twisted.internet.defer import TimeoutError
from typing import Any

class DomainError(ValueError): ...
class AuthoritativeDomainError(ValueError): ...

class DNSQueryTimeoutError(TimeoutError):
    id: Any = ...
    def __init__(self, id: Any) -> None: ...

class DNSFormatError(DomainError): ...
class DNSServerError(DomainError): ...
class DNSNameError(DomainError): ...
class DNSNotImplementedError(DomainError): ...
class DNSQueryRefusedError(DomainError): ...
class DNSUnknownError(DomainError): ...
class ResolverError(Exception): ...
