from twisted.application import internet as internet, service as service
from twisted.names import authority as authority, dns as dns, secondary as secondary, server as server
from twisted.python import usage as usage
from typing import Any

class Options(usage.Options):
    optParameters: Any = ...
    optFlags: Any = ...
    compData: Any = ...
    zones: Any = ...
    zonefiles: Any = ...
    bindfiles: Any = ...
    secondaries: Any = ...
    def __init__(self) -> None: ...
    def opt_pyzone(self, filename: Any) -> None: ...
    def opt_bindzone(self, filename: Any) -> None: ...
    def opt_secondary(self, ip_domain: Any) -> None: ...
    def opt_verbose(self) -> None: ...
    svcs: Any = ...
    def postOptions(self) -> None: ...

def makeService(config: Any): ...
