from twisted.python import log as log
from typing import Any

class ColorText:
    COLORS: Any = ...
    BOLD_COLORS: Any = ...
    BLACK: Any = ...
    RED: Any = ...
    GREEN: Any = ...
    YELLOW: Any = ...
    BLUE: Any = ...
    MAGENTA: Any = ...
    CYAN: Any = ...
    WHITE: Any = ...
    COLOR_NAMES: Any = ...
    display: Any = ...
    bold: Any = ...
    underline: Any = ...
    flash: Any = ...
    reverse: Any = ...
    def __init__(self, text: Any, fg: Any, bg: Any, display: Any, bold: Any, underline: Any, flash: Any, reverse: Any) -> None: ...

class AnsiParser:
    CURSOR_SET: Any = ...
    ERASE_SET: Any = ...
    MODE_SET: Any = ...
    ASSIGN_SET: Any = ...
    COLOR_SET: Any = ...
    SETS: Any = ...
    display: int = ...
    prepend: str = ...
    def __init__(self, defaultFG: Any, defaultBG: Any) -> None: ...
    def stripEscapes(self, string: Any): ...
    def writeString(self, colorstr: Any) -> None: ...
    def parseString(self, str: Any) -> None: ...
    bold: int = ...
    currentFG: Any = ...
    currentBG: Any = ...
    underline: int = ...
    flash: int = ...
    reverse: int = ...
    blink: int = ...
    def parseColor(self, str: Any) -> None: ...
    def parseCursor(self, cursor: Any) -> None: ...
    def parseErase(self, erase: Any) -> None: ...
    def pickColor(self, value: Any, mode: Any, BOLD: Any = ...): ...
    def formatText(self, text: Any): ...
