import tkinter.font as Tkinter
from . import ansi as ansi
from typing import Any

ttyFont: Any
fontWidth: Any
fontHeight: Any
colorKeys: Any
colorMap: Any

class VT100Frame(Tkinter.Frame):
    width: Any = ...
    height: Any = ...
    callback: Any = ...
    canvas: Any = ...
    ansiParser: Any = ...
    x: int = ...
    y: int = ...
    cursor: Any = ...
    def __init__(self, *args: Any, **kw: Any): ...
    def write(self, data: Any) -> None: ...
    def writeString(self, i: Any) -> None: ...
    def parseErase(self, erase: Any) -> None: ...
    def parseCursor(self, cursor: Any) -> None: ...
    def keyPressed(self, event: Any): ...
    def upPressed(self, event: Any) -> None: ...
    def downPressed(self, event: Any) -> None: ...
    def rightPressed(self, event: Any) -> None: ...
    def leftPressed(self, event: Any) -> None: ...
