from twisted.internet.defer import Deferred as Deferred, ensureDeferred as ensureDeferred
from twisted.python.compat import nativeString as nativeString
from twisted.web._stan import CDATA as CDATA, CharRef as CharRef, Comment as Comment, Tag as Tag, slot as slot, voidElements as voidElements
from twisted.web.error import FlattenerError as FlattenerError, UnfilledSlot as UnfilledSlot, UnsupportedType as UnsupportedType
from twisted.web.iweb import IRenderable as IRenderable
from typing import Any

def escapeForContent(data: Any): ...
def attributeEscapingDoneOutside(data: Any): ...
def writeWithAttributeEscaping(write: Any): ...
def escapedCDATA(data: Any): ...
def escapedComment(data: Any): ...
def flatten(request: Any, root: Any, write: Any): ...
def flattenString(request: Any, root: Any): ...
