from twisted.python import log as log
from twisted.python.deprecate import deprecated as deprecated
from typing import Any

def PRE(text: Any): ...
def UL(lst: Any): ...
def linkList(lst: Any): ...
def output(func: Any, *args: Any, **kw: Any): ...
