from typing import Any, Optional

class Headers:
    def __init__(self, rawHeaders: Optional[Any] = ...) -> None: ...
    def __cmp__(self, other: Any): ...
    def copy(self): ...
    def hasHeader(self, name: Any): ...
    def removeHeader(self, name: Any) -> None: ...
    def setRawHeaders(self, name: Any, values: Any) -> None: ...
    def addRawHeader(self, name: Any, value: Any) -> None: ...
    def getRawHeaders(self, name: Any, default: Optional[Any] = ...): ...
    def getAllRawHeaders(self) -> None: ...
