from twisted.web import resource as resource
from typing import Any

class RewriterResource(resource.Resource):
    resource: Any = ...
    rewriteRules: Any = ...
    def __init__(self, orig: Any, *rewriteRules: Any) -> None: ...
    def getChild(self, path: Any, request: Any): ...
    def render(self, request: Any): ...

def tildeToUsers(request: Any) -> None: ...
def alias(aliasPath: Any, sourcePath: Any): ...
