from twisted.conch import error as error
from typing import Any
from zope.interface import Interface

class _IKexAlgorithm(Interface):
    preference: Any = ...
    hashProcessor: Any = ...

class _IFixedGroupKexAlgorithm(_IKexAlgorithm):
    prime: Any = ...
    generator: Any = ...

class _IEllipticCurveExchangeKexAlgorithm(_IKexAlgorithm): ...
class _IGroupExchangeKexAlgorithm(_IKexAlgorithm): ...

class _Curve25519SHA256:
    preference: int = ...
    hashProcessor: Any = ...

class _Curve25519SHA256LibSSH:
    preference: int = ...
    hashProcessor: Any = ...

class _ECDH256:
    preference: int = ...
    hashProcessor: Any = ...

class _ECDH384:
    preference: int = ...
    hashProcessor: Any = ...

class _ECDH512:
    preference: int = ...
    hashProcessor: Any = ...

class _DHGroupExchangeSHA256:
    preference: int = ...
    hashProcessor: Any = ...

class _DHGroupExchangeSHA1:
    preference: int = ...
    hashProcessor: Any = ...

class _DHGroup14SHA1:
    preference: int = ...
    hashProcessor: Any = ...
    prime: Any = ...
    generator: int = ...

def getKex(kexAlgorithm: Any): ...
def isEllipticCurve(kexAlgorithm: Any): ...
def isFixedGroup(kexAlgorithm: Any): ...
def getHashProcessor(kexAlgorithm: Any): ...
def getDHGeneratorAndPrime(kexAlgorithm: Any): ...
def getSupportedKeyExchanges(): ...
