from twisted.internet.interfaces import IAddress as IAddress
from twisted.python import util as util
from typing import Any

class SSHTransportAddress(util.FancyEqMixin):
    compareAttributes: Any = ...
    address: Any = ...
    def __init__(self, address: Any) -> None: ...
    def __hash__(self) -> Any: ...
