from twisted.python import log as log
from typing import Any

class SSHService(log.Logger):
    name: Any = ...
    protocolMessages: Any = ...
    transport: Any = ...
    def serviceStarted(self) -> None: ...
    def serviceStopped(self) -> None: ...
    def logPrefix(self): ...
    def packetReceived(self, messageNum: Any, packet: Any): ...
