from twisted.logger import Logger as Logger
from typing import Any, Dict

class SSHService:
    name: bytes = ...
    protocolMessages: Dict[int, str] = ...
    transport: Any = ...
    def serviceStarted(self) -> None: ...
    def serviceStopped(self) -> None: ...
    def logPrefix(self): ...
    def packetReceived(self, messageNum: Any, packet: Any): ...
