from twisted.protocols.amp import Boolean as Boolean, Command as Command, Unicode as Unicode
from typing import Any

NativeString = Unicode

class Run(Command):
    arguments: Any = ...
    response: Any = ...

class Start(Command):
    arguments: Any = ...
    response: Any = ...
