from twisted.protocols.amp import Boolean as Boolean, Command as Command, String as String, Unicode as Unicode
from typing import Any

NativeString: Any

class Run(Command):
    arguments: Any = ...
    response: Any = ...

class Start(Command):
    arguments: Any = ...
    response: Any = ...
