from twisted.internet.protocol import FileWrapper as FileWrapper
from twisted.python.log import startLoggingWithObserver as startLoggingWithObserver, textFromEventDict as textFromEventDict
from twisted.trial._dist.options import WorkerOptions as WorkerOptions
from typing import Any

class WorkerLogObserver:
    protocol: Any = ...
    def __init__(self, protocol: Any) -> None: ...
    def emit(self, eventDict: Any) -> None: ...

def main(_fdopen: Any = ...) -> None: ...
