from twisted import copyright as copyright
from twisted.application import app as app, internet as internet, service as service
from twisted.python import log as log
from typing import Any

class ServerOptions(app.ServerOptions):
    synopsis: str = ...
    optFlags: Any = ...
    def opt_version(self) -> None: ...

class WindowsApplicationRunner(app.ApplicationRunner):
    oldstdout: Any = ...
    oldstderr: Any = ...
    def preApplication(self) -> None: ...
    def postApplication(self) -> None: ...
