from twisted.conch.error import ConchError as ConchError
from twisted.conch.interfaces import IConchUser as IConchUser
from twisted.conch.ssh.connection import OPEN_UNKNOWN_CHANNEL_TYPE as OPEN_UNKNOWN_CHANNEL_TYPE
from twisted.python import log as log
from twisted.python.compat import nativeString as nativeString
from typing import Any

class ConchUser:
    channelLookup: Any = ...
    subsystemLookup: Any = ...
    def __init__(self) -> None: ...
    def lookupChannel(self, channelType: Any, windowSize: Any, maxPacket: Any, data: Any): ...
    def lookupSubsystem(self, subsystem: Any, data: Any): ...
    def gotGlobalRequest(self, requestType: Any, data: Any): ...
