from typing import Any
from zope.interface import Interface

class IConchUser(Interface):
    conn: Any = ...
    def lookupChannel(channelType: Any, windowSize: Any, maxPacket: Any, data: Any) -> None: ...
    def lookupSubsystem(subsystem: Any, data: Any) -> None: ...
    def gotGlobalRequest(requestType: Any, data: Any) -> None: ...

class ISession(Interface):
    def getPty(term: Any, windowSize: Any, modes: Any) -> None: ...
    def openShell(proto: Any) -> None: ...
    def execCommand(proto: Any, command: Any) -> None: ...
    def windowChanged(newWindowSize: Any) -> None: ...
    def eofReceived() -> None: ...
    def closed() -> None: ...

class EnvironmentVariableNotPermitted(ValueError): ...

class ISessionSetEnv(Interface):
    def setEnv(name: Any, value: Any) -> None: ...

class ISFTPServer(Interface):
    avatar: Any = ...
    def gotVersion(otherVersion: Any, extData: Any): ...
    def openFile(filename: Any, flags: Any, attrs: Any) -> None: ...
    def removeFile(filename: Any) -> None: ...
    def renameFile(oldpath: Any, newpath: Any) -> None: ...
    def makeDirectory(path: Any, attrs: Any) -> None: ...
    def removeDirectory(path: Any) -> None: ...
    def openDirectory(path: Any) -> None: ...
    def getAttrs(path: Any, followLinks: Any) -> None: ...
    def setAttrs(path: Any, attrs: Any) -> None: ...
    def readLink(path: Any) -> None: ...
    def makeLink(linkPath: Any, targetPath: Any) -> None: ...
    def realPath(path: Any) -> None: ...
    def extendedRequest(extendedName: Any, extendedData: Any) -> None: ...

class IKnownHostEntry(Interface):
    def matchesKey(key: Any) -> None: ...
    def matchesHost(hostname: Any) -> None: ...
    def toString() -> None: ...

class ISFTPFile(Interface):
    def close() -> None: ...
    def readChunk(offset: Any, length: Any) -> None: ...
    def writeChunk(offset: Any, data: Any) -> None: ...
    def getAttrs() -> None: ...
    def setAttrs(attrs: Any) -> None: ...
