from twisted.internet import reactor as reactor
from typing import Any

class BufferingMixin:
    data: Any = ...
    DELAY: float = ...
    def schedule(self): ...
    def reschedule(self, token: Any) -> None: ...
    def write(self, data: Any) -> None: ...
    def flush(self) -> None: ...
