from twisted.application import strports as strports
from twisted.conch import unix as unix
from twisted.conch.openssh_compat import factory as factory
from twisted.cred import portal as portal, strcred as strcred
from twisted.python import usage as usage
from typing import Any

class Options(usage.Options, strcred.AuthOptionMixin):
    synopsis: str = ...
    longdesc: str = ...
    optParameters: Any = ...
    compData: Any = ...
    def __init__(self, *a: Any, **kw: Any) -> None: ...
    def addChecker(self, checker: Any) -> None: ...

def makeService(config: Any): ...
