from twisted import plugin as plugin
from twisted.conch.checkers import SSHPublicKeyChecker as SSHPublicKeyChecker, UNIXAuthorizedKeysFiles as UNIXAuthorizedKeysFiles
from twisted.cred.strcred import ICheckerFactory as ICheckerFactory
from typing import Any

sshKeyCheckerFactoryHelp: str

class SSHKeyCheckerFactory:
    authType: str = ...
    authHelp: Any = ...
    argStringFormat: str = ...
    credentialInterfaces: Any = ...
    def generateChecker(self, argstring: str = ...): ...

theSSHKeyCheckerFactory: Any
