from twisted import plugin as plugin
from twisted.cred.checkers import FilePasswordDB as FilePasswordDB
from twisted.cred.credentials import IUsernameHashedPassword as IUsernameHashedPassword, IUsernamePassword as IUsernamePassword
from twisted.cred.strcred import ICheckerFactory as ICheckerFactory
from typing import Any

fileCheckerFactoryHelp: str
invalidFileWarning: str

class FileCheckerFactory:
    authType: str = ...
    authHelp: Any = ...
    argStringFormat: str = ...
    credentialInterfaces: Any = ...
    errorOutput: Any = ...
    def generateChecker(self, argstring: Any): ...

theFileCheckerFactory: Any
