from twisted.plugin import IPlugin as IPlugin
from twisted.trial.itrial import IReporter as IReporter
from typing import Any

class _Reporter:
    name: Any = ...
    module: Any = ...
    description: Any = ...
    longOpt: Any = ...
    shortOpt: Any = ...
    klass: Any = ...
    def __init__(self, name: Any, module: Any, description: Any, longOpt: Any, shortOpt: Any, klass: Any) -> None: ...

Tree: Any
BlackAndWhite: Any
Minimal: Any
Classic: Any
Timing: Any
Subunit: Any
