from ._observer import ILogObserver as ILogObserver
from typing import Any

class LimitedHistoryLogObserver:
    def __init__(self, size: Any = ...) -> None: ...
    def __call__(self, event: Any) -> None: ...
    def replayTo(self, otherObserver: Any) -> None: ...
