from ._interfaces import ILogObserver as ILogObserver, LogEvent as LogEvent
from typing import Optional

class LimitedHistoryLogObserver:
    def __init__(self, size: Optional[int]=...) -> None: ...
    def __call__(self, event: LogEvent) -> None: ...
    def replayTo(self, otherObserver: ILogObserver) -> None: ...
