from ._format import formatEventAsClassicLogText as formatEventAsClassicLogText, formatTime as formatTime, timeFormatRFC3339 as timeFormatRFC3339
from ._observer import ILogObserver as ILogObserver
from twisted.python.compat import ioType as ioType, unicode as unicode
from typing import Any

class FileLogObserver:
    formatEvent: Any = ...
    def __init__(self, outFile: Any, formatEvent: Any) -> None: ...
    def __call__(self, event: Any) -> None: ...

def textFileLogObserver(outFile: Any, timeFormat: Any = ...): ...
