from ._format import formatEventAsClassicLogText as formatEventAsClassicLogText, formatTime as formatTime, timeFormatRFC3339 as timeFormatRFC3339
from ._interfaces import ILogObserver as ILogObserver, LogEvent as LogEvent
from twisted.python.compat import ioType as ioType
from typing import Any, Callable, IO, Optional

class FileLogObserver:
    formatEvent: Any = ...
    def __init__(self, outFile: IO[Any], formatEvent: Callable[[LogEvent], Optional[str]]) -> None: ...
    def __call__(self, event: LogEvent) -> None: ...

def textFileLogObserver(outFile: IO[Any], timeFormat: Optional[str]=...) -> FileLogObserver: ...
