from twisted.python.compat import unicode as unicode
from typing import Any

aFormatter: Any

class KeyFlattener:
    keys: Any = ...
    def __init__(self): ...
    def flatKey(self, fieldName: Any, formatSpec: Any, conversion: Any): ...

def flattenEvent(event: Any) -> None: ...
def extractField(field: Any, event: Any): ...
def flatFormat(event: Any): ...
