from ._file import FileLogObserver as FileLogObserver
from ._flatten import flattenEvent as flattenEvent
from ._levels import LogLevel as LogLevel
from ._logger import Logger as Logger
from twisted.python.compat import unicode as unicode
from twisted.python.failure import Failure as Failure
from typing import Any, Optional

log: Any

def failureAsJSON(failure: Any): ...
def asBytes(obj: Any): ...
def failureFromJSON(failureDict: Any): ...

classInfo: Any
uuidToLoader: Any

def objectLoadHook(aDict: Any): ...
def objectSaveHook(pythonObject: Any): ...
def eventAsJSON(event: Any): ...
def eventFromJSON(eventText: Any): ...
def jsonFileLogObserver(outFile: Any, recordSeparator: str = ...): ...
def eventsFromJSONLogFile(inFile: Any, recordSeparator: Optional[Any] = ..., bufferSize: int = ...): ...
