from ._format import formatEvent as formatEvent
from ._levels import LogLevel as LogLevel
from ._observer import ILogObserver as ILogObserver
from ._stdlib import StringifiableFromEvent as StringifiableFromEvent, fromStdlibLogLevelMapping as fromStdlibLogLevelMapping
from typing import Any

class LegacyLogObserverWrapper:
    legacyObserver: Any = ...
    def __init__(self, legacyObserver: Any) -> None: ...
    def __call__(self, event: Any) -> None: ...

def publishToNewObserver(observer: Any, eventDict: Any, textFromEventDict: Any) -> None: ...
