from constantly import Names
from typing import Any

class InvalidLogLevelError(Exception):
    level: Any = ...
    def __init__(self, level: Any) -> None: ...

class LogLevel(Names):
    debug: Any = ...
    info: Any = ...
    warn: Any = ...
    error: Any = ...
    critical: Any = ...
    @classmethod
    def levelWithName(cls, name: Any): ...
