from constantly import NamedConstant, Names
from typing import Any

class InvalidLogLevelError(Exception):
    level: Any = ...
    def __init__(self, level: NamedConstant) -> None: ...

class LogLevel(Names):
    debug: Any = ...
    info: Any = ...
    warn: Any = ...
    error: Any = ...
    critical: Any = ...
    @classmethod
    def levelWithName(cls: Any, name: str) -> NamedConstant: ...
