from ._logger import Logger as Logger
from twisted.python.failure import Failure as Failure
from typing import Any
from zope.interface import Interface

OBSERVER_DISABLED: str

class ILogObserver(Interface):
    def __call__(event: Any) -> None: ...

class LogPublisher:
    log: Any = ...
    def __init__(self, *observers: Any) -> None: ...
    def addObserver(self, observer: Any) -> None: ...
    def removeObserver(self, observer: Any) -> None: ...
    def __call__(self, event: Any) -> None: ...
