from ._format import formatEvent as formatEvent
from ._interfaces import ILogObserver as ILogObserver, LogEvent as LogEvent
from ._levels import LogLevel as LogLevel
from constantly import NamedConstant as NamedConstant
from twisted.python.compat import currentframe as currentframe
from typing import Any, Mapping

toStdlibLogLevelMapping: Mapping[NamedConstant, int]
fromStdlibLogLevelMapping: Any

class STDLibLogObserver:
    defaultStackDepth: int = ...
    logger: Any = ...
    stackDepth: Any = ...
    def __init__(self, name: str=..., stackDepth: int=...) -> None: ...
    def __call__(self, event: LogEvent) -> None: ...

class StringifiableFromEvent:
    event: Any = ...
    def __init__(self, event: LogEvent) -> None: ...
    def __bytes__(self) -> bytes: ...
