from ._format import formatEvent as formatEvent
from ._levels import LogLevel as LogLevel
from ._observer import ILogObserver as ILogObserver
from twisted.python.compat import currentframe as currentframe, unicode as unicode
from typing import Any

toStdlibLogLevelMapping: Any
fromStdlibLogLevelMapping: Any

class STDLibLogObserver:
    defaultStackDepth: int = ...
    logger: Any = ...
    stackDepth: Any = ...
    def __init__(self, name: str = ..., stackDepth: Any = ...) -> None: ...
    def __call__(self, event: Any) -> None: ...

class StringifiableFromEvent:
    event: Any = ...
    def __init__(self, event: Any) -> None: ...
    def __unicode__(self): ...
    def __bytes__(self): ...
