from twisted.python import compat as compat
from typing import Any

class InvalidProxyHeader(Exception): ...
class InvalidNetworkProtocol(InvalidProxyHeader): ...
class MissingAddressData(InvalidProxyHeader): ...

def convertError(sourceType: Any, targetType: Any) -> None: ...
