from ._interfaces import IProxyInfo as IProxyInfo
from typing import Any

class ProxyInfo:
    header: Any = ...
    source: Any = ...
    destination: Any = ...
    def __init__(self, header: Any, source: Any, destination: Any) -> None: ...
