from twisted.cred import credentials as credentials, error as error
from twisted.web.iweb import ICredentialFactory as ICredentialFactory
from typing import Any

class BasicCredentialFactory:
    scheme: bytes = ...
    authenticationRealm: Any = ...
    def __init__(self, authenticationRealm: Any) -> None: ...
    def getChallenge(self, request: Any): ...
    def decode(self, response: Any, request: Any): ...
