class WordsError(Exception): ...
class NoSuchUser(WordsError): ...
class DuplicateUser(WordsError): ...
class NoSuchGroup(WordsError): ...
class DuplicateGroup(WordsError): ...
class AlreadyLoggedIn(WordsError): ...
