from typing import Any

class AccountManager:
    accounts: Any = ...
    def __init__(self) -> None: ...
    def getSnapShot(self): ...
    def isEmpty(self): ...
    def getConnectionInfo(self): ...
    def addAccount(self, account: Any) -> None: ...
    def delAccount(self, accountName: Any) -> None: ...
    def connect(self, accountName: Any, chatui: Any): ...
    def disconnect(self, accountName: Any) -> None: ...
    def quit(self) -> None: ...
