from typing import Any

class Enum:
    group: Any = ...
    label: Any = ...
    def __init__(self, label: Any) -> None: ...

class StatusEnum(Enum):
    group: str = ...

OFFLINE: Any
ONLINE: Any
AWAY: Any

class OfflineError(Exception): ...
