from twisted.plugin import IPlugin as IPlugin, getPlugins as getPlugins
from twisted.python.reflect import namedAny as namedAny
from typing import Any
from zope.interface import Interface

class IReactorInstaller(Interface):
    shortName: Any = ...
    description: Any = ...
    def install() -> None: ...

class NoSuchReactor(KeyError): ...

class Reactor:
    shortName: Any = ...
    moduleName: Any = ...
    description: Any = ...
    def __init__(self, shortName: Any, moduleName: Any, description: Any) -> None: ...
    def install(self) -> None: ...

def getReactorTypes(): ...
def installReactor(shortName: Any): ...
