from twisted.cred import credentials
from typing import Any

class CramMD5ClientAuthenticator:
    user: Any = ...
    def __init__(self, user: Any) -> None: ...
    def getName(self): ...
    def challengeResponse(self, secret: Any, chal: Any): ...

class LOGINAuthenticator:
    user: Any = ...
    challengeResponse: Any = ...
    def __init__(self, user: Any) -> None: ...
    def getName(self): ...
    def challengeUsername(self, secret: Any, chal: Any): ...
    def challengeSecret(self, secret: Any, chal: Any): ...

class PLAINAuthenticator:
    user: Any = ...
    def __init__(self, user: Any) -> None: ...
    def getName(self): ...
    def challengeResponse(self, secret: Any, chal: Any): ...

class LOGINCredentials(credentials.UsernamePassword):
    challenges: Any = ...
    responses: Any = ...
    def __init__(self) -> None: ...
    def getChallenge(self): ...
    def setResponse(self, response: Any) -> None: ...
    def moreChallenges(self): ...

class PLAINCredentials(credentials.UsernamePassword):
    def __init__(self) -> None: ...
    def getChallenge(self): ...
    def setResponse(self, response: Any) -> None: ...
    def moreChallenges(self): ...
