from twisted.internet.address import UNIXAddress as UNIXAddress
from twisted.mail import smtp as smtp
from twisted.python import log as log
from typing import Any

class DomainQueuer:
    service: Any = ...
    authed: Any = ...
    def __init__(self, service: Any, authenticated: bool = ...) -> None: ...
    def exists(self, user: Any): ...
    def willRelay(self, address: Any, protocol: Any): ...
    def startMessage(self, user: Any): ...

class RelayerMixin:
    messages: Any = ...
    names: Any = ...
    def loadMessages(self, messagePaths: Any) -> None: ...
    def getMailFrom(self): ...
    def getMailTo(self): ...
    def getMailData(self): ...
    def sentMail(self, code: Any, resp: Any, numOk: Any, addresses: Any, log: Any) -> None: ...

class SMTPRelayer(RelayerMixin, smtp.SMTPClient):
    def __init__(self, messagePaths: Any, *args: Any, **kw: Any) -> None: ...

class ESMTPRelayer(RelayerMixin, smtp.ESMTPClient):
    def __init__(self, messagePaths: Any, *args: Any, **kw: Any) -> None: ...
