from twisted.application import internet as internet
from twisted.cred import checkers as checkers, portal as portal, strcred as strcred
from twisted.protocols import ftp as ftp
from twisted.python import deprecate as deprecate, usage as usage, versions as versions
from typing import Any

class Options(usage.Options, strcred.AuthOptionMixin):
    synopsis: str = ...
    optParameters: Any = ...
    compData: Any = ...
    longdesc: str = ...
    def __init__(self, *a: Any, **kw: Any) -> None: ...
    def opt_password_file(self, filename: Any) -> None: ...

def makeService(config: Any): ...
