from twisted.application import internet as internet
from twisted.protocols import socks as socks
from twisted.python import usage as usage
from typing import Any

class Options(usage.Options):
    synopsis: str = ...
    optParameters: Any = ...
    compData: Any = ...
    longdesc: str = ...

def makeService(config: Any): ...
