from twisted.logger import Logger as Logger
from typing import Any
from zope.interface import Interface

class IPIDFile(Interface):
    def read() -> None: ...
    def writeRunningPID() -> None: ...
    def remove() -> None: ...
    def isRunning() -> None: ...
    def __enter__() -> None: ...
    def __exit__(excType: Any, excValue: Any, traceback: Any) -> None: ...

class PIDFile:
    filePath: Any = ...
    def __init__(self, filePath: Any) -> None: ...
    def read(self): ...
    def writeRunningPID(self) -> None: ...
    def remove(self) -> None: ...
    def isRunning(self): ...
    def __enter__(self): ...
    def __exit__(self, excType: Any, excValue: Any, traceback: Any) -> None: ...

class NonePIDFile:
    def __init__(self) -> None: ...
    def read(self) -> None: ...
    def writeRunningPID(self) -> None: ...
    def remove(self) -> None: ...
    def isRunning(self): ...
    def __enter__(self): ...
    def __exit__(self, excType: Any, excValue: Any, traceback: Any) -> None: ...

nonePIDFile: Any

class AlreadyRunningError(Exception): ...
class InvalidPIDFileError(Exception): ...
class StalePIDFileError(Exception): ...
class NoPIDFound(Exception): ...
