from . import IWorker as IWorker
from ._convenience import Quit as Quit
from typing import Any

NoMoreWork: Any

class MemoryWorker:
    def __init__(self, pending: Any = ...) -> None: ...
    def do(self, work: Any) -> None: ...
    def quit(self) -> None: ...

def createMemoryWorker(): ...
