from ._convenience import Quit as Quit
from ._ithreads import IExclusiveWorker as IExclusiveWorker
from typing import Any

class ThreadWorker:
    def __init__(self, startThread: Any, queue: Any) -> None: ...
    def do(self, task: Any) -> None: ...
    def quit(self) -> None: ...

class LockWorker:
    def __init__(self, lock: Any, local: Any) -> None: ...
    def do(self, work: Any) -> None: ...
    def quit(self) -> None: ...
