from typing import Any, Optional

algorithms: Any

def calcHA1(pszAlg: Any, pszUserName: Any, pszRealm: Any, pszPassword: Any, pszNonce: Any, pszCNonce: Any, preHA1: Optional[Any] = ...): ...
def calcHA2(algo: Any, pszMethod: Any, pszDigestUri: Any, pszQop: Any, pszHEntity: Any): ...
def calcResponse(HA1: Any, HA2: Any, algo: Any, pszNonce: Any, pszNonceCount: Any, pszCNonce: Any, pszQop: Any): ...
