class Unauthorized(Exception): ...
class LoginFailed(Exception): ...
class UnauthorizedLogin(LoginFailed, Unauthorized): ...
class UnhandledCredentials(LoginFailed): ...
class LoginDenied(LoginFailed): ...
