from twisted.cred import error as error
from twisted.internet import defer as defer
from twisted.internet.defer import maybeDeferred as maybeDeferred
from twisted.python import failure as failure, reflect as reflect
from typing import Any
from zope.interface import Interface

class IRealm(Interface):
    def requestAvatar(avatarId: Any, mind: Any, *interfaces: Any) -> None: ...

class Portal:
    realm: Any = ...
    checkers: Any = ...
    def __init__(self, realm: Any, checkers: Any = ...) -> None: ...
    def listCredentialsInterfaces(self): ...
    def registerChecker(self, checker: Any, *credentialInterfaces: Any) -> None: ...
    def login(self, credentials: Any, mind: Any, *interfaces: Any): ...
