from twisted.internet import fdesc as fdesc, process as process, reactor as reactor
from twisted.internet.protocol import Protocol as Protocol, ServerFactory as ServerFactory
from twisted.protocols import wire as wire
from typing import Any

internalProtocols: Any

class InetdProtocol(Protocol):
    def connectionMade(self) -> None: ...

class InetdFactory(ServerFactory):
    protocol: Any = ...
    stderrFile: Any = ...
    service: Any = ...
    def __init__(self, service: Any) -> None: ...
