from twisted.python import usage as usage
from twisted.runner.procmon import ProcessMonitor as ProcessMonitor
from typing import Any

class Options(usage.Options):
    synopsis: str = ...
    optParameters: Any = ...
    optFlags: Any = ...
    longdesc: str = ...
    def parseArgs(self, *args: Any) -> None: ...
    def postOptions(self) -> None: ...

def makeService(config: Any): ...
