from twisted.python import components as components
from twisted.trial import itrial as itrial, reporter as reporter
from typing import Any

pyunit: Any

class TestSuite(pyunit.TestSuite):
    def run(self, result: Any): ...

class TestDecorator:
    def __call__(self, result: Any): ...
    def run(self, result: Any): ...

def decorate(test: Any, decorator: Any): ...

class _PyUnitTestCaseAdapter(TestDecorator): ...

class _BrokenIDTestCaseAdapter(_PyUnitTestCaseAdapter):
    def id(self): ...

class _ForceGarbageCollectionDecorator(TestDecorator):
    def run(self, result: Any) -> None: ...
