import zope.interface as zi
from typing import Any, Optional

class ITestCase(zi.Interface):
    failureException: Any = ...
    def __call__(result: Any) -> None: ...
    def countTestCases() -> None: ...
    def id() -> None: ...
    def run(result: Any) -> None: ...
    def shortDescription() -> None: ...

class IReporter(zi.Interface):
    stream: Any = ...
    tbformat: Any = ...
    args: Any = ...
    shouldStop: Any = ...
    separator: Any = ...
    testsRun: Any = ...
    def startTest(method: Any) -> None: ...
    def stopTest(method: Any) -> None: ...
    def startSuite(name: Any) -> None: ...
    def endSuite(name: Any) -> None: ...
    def cleanupErrors(errs: Any) -> None: ...
    def upDownError(userMeth: Any, warn: bool = ..., printStatus: bool = ...) -> None: ...
    def addSuccess(test: Any) -> None: ...
    def addError(test: Any, error: Any) -> None: ...
    def addFailure(test: Any, failure: Any) -> None: ...
    def addExpectedFailure(test: Any, failure: Any, todo: Optional[Any] = ...) -> None: ...
    def addUnexpectedSuccess(test: Any, todo: Optional[Any] = ...) -> None: ...
    def addSkip(test: Any, reason: Any) -> None: ...
    def printSummary() -> None: ...
    def printErrors() -> None: ...
    def write(string: Any) -> None: ...
    def writeln(string: Any) -> None: ...
    def wasSuccessful() -> None: ...
    def done() -> None: ...
