import zope.interface as zi
from typing import Any, Optional

class ITestCase(zi.Interface):
    failureException: Any = ...
    def __call__(result: Any) -> None: ...
    def countTestCases() -> None: ...
    def id() -> None: ...
    def run(result: Any) -> None: ...
    def shortDescription() -> None: ...

class IReporter(zi.Interface):
    shouldStop: Any = ...
    testsRun: Any = ...
    def startTest(method: Any) -> None: ...
    def stopTest(method: Any) -> None: ...
    def addSuccess(test: Any) -> None: ...
    def addError(test: Any, error: Any) -> None: ...
    def addFailure(test: Any, failure: Any) -> None: ...
    def addExpectedFailure(test: Any, failure: Any, todo: Optional[Any] = ...) -> None: ...
    def addUnexpectedSuccess(test: Any, todo: Optional[Any] = ...) -> None: ...
    def addSkip(test: Any, reason: Any) -> None: ...
    def wasSuccessful() -> None: ...
    def done() -> None: ...
