from typing import Any, Optional

DEFAULT_TIMEOUT_DURATION: float

class DirtyReactorAggregateError(Exception):
    delayedCalls: Any = ...
    selectables: Any = ...
    def __init__(self, delayedCalls: Any, selectables: Optional[Any] = ...) -> None: ...

class _Janitor:
    test: Any = ...
    result: Any = ...
    reactor: Any = ...
    def __init__(self, test: Any, result: Any, reactor: Optional[Any] = ...) -> None: ...
    def postCaseCleanup(self): ...
    def postClassCleanup(self) -> None: ...

def acquireAttribute(objects: Any, attr: Any, default: Any = ...): ...
def excInfoOrFailureToExcInfo(err: Any): ...
def suppress(action: str = ..., **kwarg: Any): ...

class _NoTrialMarker(Exception): ...
class _WorkingDirectoryBusy(Exception): ...
