from twisted.copyright import version as version
from twisted.internet import reactor as reactor
from twisted.logger import Logger as Logger, textFileLogObserver as textFileLogObserver
from twisted.mail import smtp as smtp
from typing import Any

GLOBAL_CFG: str
LOCAL_CFG: Any
SMARTHOST: str
ERROR_FMT: str

class Options: ...

def getlogin(): ...
def parseOptions(argv: Any): ...

class Configuration:
    allowUIDs: Any = ...
    denyUIDs: Any = ...
    allowGIDs: Any = ...
    denyGIDs: Any = ...
    useraccess: str = ...
    groupaccess: str = ...
    identities: Any = ...
    smarthost: Any = ...
    domain: Any = ...
    defaultAccess: bool = ...
    def __init__(self) -> None: ...

def loadConfig(path: Any): ...
def success(result: Any) -> None: ...

failed: Any

def failure(f: Any) -> None: ...
def sendmail(host: Any, options: Any, ident: Any) -> None: ...
def senderror(failure: Any, options: Any): ...
def deny(conf: Any): ...
def run() -> None: ...
