from twisted.protocols import basic as basic
from typing import Any

class Finger(basic.LineReceiver):
    def lineReceived(self, line: Any): ...
    def forwardQuery(self, slash_w: Any, user: Any, host: Any) -> None: ...
    def getDomain(self, slash_w: Any) -> None: ...
    def getUser(self, slash_w: Any, user: Any) -> None: ...
