from twisted import copyright as copyright
from twisted.web import http as http
from typing import Any

class ShoutcastClient(http.HTTPClient):
    userAgent: Any = ...
    path: Any = ...
    got_metadata: bool = ...
    metaint: Any = ...
    metamode: str = ...
    databuffer: str = ...
    def __init__(self, path: str = ...) -> None: ...
    def connectionMade(self) -> None: ...
    def lineReceived(self, line: Any) -> None: ...
    def handleHeader(self, key: Any, value: Any) -> None: ...
    handleResponsePart: Any = ...
    def handleEndHeaders(self) -> None: ...
    def handleResponsePart_with_metadata(self, data: Any) -> None: ...
    remaining: Any = ...
    def handle_length(self) -> None: ...
    def handle_mp3(self): ...
    def handle_meta(self): ...
    def parseMetadata(self, data: Any): ...
    def gotMetaData(self, metadata: Any) -> None: ...
    def gotMP3Data(self, data: Any) -> None: ...
