from twisted.internet import protocol as protocol
from typing import Any

class StatefulProtocol(protocol.Protocol):
    def makeConnection(self, transport: Any) -> None: ...
    def getInitialState(self) -> None: ...
    def dataReceived(self, data: Any) -> None: ...
