from typing import Any

class _BaseSentence:
    ALLOWED_ATTRIBUTES: Any = ...
    def __init__(self, sentenceData: Any) -> None: ...
    @property
    def presentAttributes(self): ...
    def __getattr__(self, name: Any): ...

class _PositioningSentenceProducerMixin:
    @classmethod
    def getSentenceAttributes(cls): ...
