from typing import Any
from zope.interface import Interface

class IPositioningReceiver(Interface):
    def positionReceived(latitude: Any, longitude: Any) -> None: ...
    def positionErrorReceived(positionError: Any) -> None: ...
    def timeReceived(time: Any) -> None: ...
    def headingReceived(heading: Any) -> None: ...
    def altitudeReceived(altitude: Any) -> None: ...
    def speedReceived(speed: Any) -> None: ...
    def climbReceived(climb: Any) -> None: ...
    def beaconInformationReceived(beaconInformation: Any) -> None: ...

class IPositioningBeacon(Interface):
    identifier: Any = ...

class INMEAReceiver(Interface):
    def sentenceReceived(sentence: Any) -> None: ...
