from typing import Any
from zope.interface import Interface

class IRawDatagramProtocol(Interface):
    def addProto(num: Any, proto: Any) -> None: ...
    def datagramReceived(data: Any, partial: Any, source: Any, dest: Any, protocol: Any, version: Any, ihl: Any, tos: Any, tot_len: Any, fragment_id: Any, fragment_offset: Any, dont_fragment: Any, more_fragments: Any, ttl: Any) -> None: ...

class IRawPacketProtocol(Interface):
    def addProto(num: Any, proto: Any) -> None: ...
    def datagramReceived(data: Any, partial: Any, dest: Any, source: Any, protocol: Any) -> None: ...
