from zope.interface import Interface

class IRawDatagramProtocol(Interface):
    def addProto() -> None: ...
    def datagramReceived() -> None: ...

class IRawPacketProtocol(Interface):
    def addProto() -> None: ...
    def datagramReceived() -> None: ...
