import ctypes.util
from twisted.python.filepath import FilePath as FilePath
from typing import Any

class INotifyError(Exception): ...

def init() -> int: ...
def add(fd: int, path: FilePath, mask: int) -> int: ...
def remove(fd: int, wd: int) -> None: ...
def initializeModule(libc: ctypes.CDLL) -> None: ...

name: Any
libc: Any
