from typing import Any

class INotifyError(Exception): ...

def init(): ...
def add(fd: Any, path: Any, mask: Any): ...
def remove(fd: Any, wd: Any) -> None: ...
def initializeModule(libc: Any) -> None: ...

name: Any
libc: Any
