from distutils.command import build_ext
from setuptools import Extension
from setuptools.command.build_py import build_py
from typing import Any

STATIC_PACKAGE_METADATA: Any

class ConditionalExtension(Extension):
    condition: Any = ...
    def __init__(self, *args: Any, **kwargs: Any): ...

def getSetupArgs(extensions: Any = ..., readme: str = ...): ...

class BuildPy3(build_py):
    def find_package_modules(self, package: Any, package_dir: Any): ...

class build_ext_twisted(build_ext.build_ext):
    define_macros: Any = ...
    extensions: Any = ...
    def prepare_extensions(self) -> None: ...
    def build_extensions(self) -> None: ...

notPortedModules: Any
