from datetime import tzinfo
from typing import Any, Optional

class FixedOffsetTimeZone(tzinfo):
    offset: Any = ...
    name: Any = ...
    def __init__(self, offset: Any, name: Optional[Any] = ...) -> None: ...
    @classmethod
    def fromSignHoursMinutes(cls, sign: Any, hours: Any, minutes: Any): ...
    @classmethod
    def fromLocalTimeStamp(cls, timeStamp: Any): ...
    def utcoffset(self, dt: Any): ...
    def dst(self, dt: Any): ...
    def tzname(self, dt: Any): ...

UTC: Any
