from datetime import datetime as DateTime, timedelta as TimeDelta, tzinfo as TZInfo
from typing import Any, Optional

class FixedOffsetTimeZone(TZInfo):
    offset: Any = ...
    name: Any = ...
    def __init__(self, offset: TimeDelta, name: Optional[str]=...) -> None: ...
    @classmethod
    def fromSignHoursMinutes(cls: Any, sign: str, hours: int, minutes: int) -> FixedOffsetTimeZone: ...
    @classmethod
    def fromLocalTimeStamp(cls: Any, timeStamp: float) -> FixedOffsetTimeZone: ...
    def utcoffset(self, dt: Optional[DateTime]) -> TimeDelta: ...
    def dst(self, dt: Optional[DateTime]) -> TimeDelta: ...
    def tzname(self, dt: Optional[DateTime]) -> str: ...

UTC: Any
