import urllib.parse as urllib_parse
from collections.abc import Sequence as Sequence
from functools import reduce as reduce
from html import escape as escape
from http import cookiejar as cookielib
from io import IOBase, StringIO as NativeStringIO
from sys import intern as intern
from typing import Any, AnyStr, Optional
from urllib.parse import quote as urlquote, unquote as urlunquote

FileType = IOBase
frozenset = frozenset
InstanceType = object
izip = zip
long = int
range = range
raw_input = input
set = set
StringType = str
unichr = chr
unicode = str
xrange = range

def iteritems(d: Any): ...
def itervalues(d: Any): ...
def items(d: Any): ...
def execfile(filename: Any, globals: Any, locals: Optional[Any] = ...) -> None: ...
def cmp(a: Any, b: Any): ...
def comparable(klass: Any): ...
def nativeString(s: AnyStr) -> str: ...
def reraise(exception: Any, traceback: Any) -> None: ...
def iterbytes(originalBytes: Any) -> None: ...
def intToBytes(i: int) -> bytes: ...
def lazyByteSlice(object: Any, offset: int = ..., size: Optional[Any] = ...): ...
def networkString(s: str) -> bytes: ...
def bytesEnviron(): ...

# Names in __all__ with no definition:
#   _get_async_param
