from typing import Any

class _UserRecord:
    pw_name: Any = ...
    pw_passwd: Any = ...
    pw_uid: Any = ...
    pw_gid: Any = ...
    pw_gecos: Any = ...
    pw_dir: Any = ...
    pw_shell: Any = ...
    def __init__(self, name: Any, password: Any, uid: Any, gid: Any, gecos: Any, home: Any, shell: Any) -> None: ...
    def __len__(self): ...
    def __getitem__(self, index: Any): ...

class UserDatabase:
    def __init__(self) -> None: ...
    def addUser(self, username: Any, password: Any, uid: Any, gid: Any, gecos: Any, home: Any, shell: Any) -> None: ...
    def getpwuid(self, uid: Any): ...
    def getpwnam(self, name: Any): ...
    def getpwall(self): ...

class _ShadowRecord:
    sp_nam: Any = ...
    sp_pwd: Any = ...
    sp_lstchg: Any = ...
    sp_min: Any = ...
    sp_max: Any = ...
    sp_warn: Any = ...
    sp_inact: Any = ...
    sp_expire: Any = ...
    sp_flag: Any = ...
    def __init__(self, username: Any, password: Any, lastChange: Any, min: Any, max: Any, warn: Any, inact: Any, expire: Any, flag: Any) -> None: ...
    def __len__(self): ...
    def __getitem__(self, index: Any): ...

class ShadowDatabase:
    def __init__(self) -> None: ...
    def addUser(self, username: Any, password: Any, lastChange: Any, min: Any, max: Any, warn: Any, inact: Any, expire: Any, flag: Any) -> None: ...
    def getspnam(self, username: Any): ...
    def getspall(self): ...
