from typing import Any

class FilesystemLock:
    clean: Any = ...
    locked: bool = ...
    name: Any = ...
    def __init__(self, name: Any) -> None: ...
    def lock(self): ...
    def unlock(self) -> None: ...

def isLocked(name: Any): ...
