from typing import Any

class MonkeyPatcher:
    def __init__(self, *patches: Any) -> None: ...
    def addPatch(self, obj: Any, name: Any, value: Any) -> None: ...
    def patch(self) -> None: ...
    def restore(self) -> None: ...
    def runWithPatches(self, f: Any, *args: Any, **kw: Any): ...
