from twisted.python import log as log, reflect as reflect
from typing import Any

lastRebuild: Any

class Sensitive:
    lastRebuild: Any = ...
    def needRebuildUpdate(self): ...
    def rebuildUpToDate(self) -> None: ...
    def latestVersionOf(self, anObject: Any): ...

def latestFunction(oldFunc: Any): ...
def latestClass(oldClass: Any): ...

class RebuildError(Exception): ...

def updateInstance(self) -> None: ...
def __injectedgetattr__(self, name: Any): ...
def rebuild(module: Any, doLog: int = ...): ...
