from typing import Any

class DirectoryExists(OSError): ...
class DirectoryDoesntExist(OSError): ...
class CommandFailed(OSError): ...

def sh(command: Any, null: bool = ..., prompt: bool = ...) -> None: ...
def runChdirSafe(f: Any, *args: Any, **kw: Any): ...
