from typing import Any, Optional

def shortPythonVersion(): ...

knownPlatforms: Any

class Platform:
    type: Any = ...
    seconds: Any = ...
    def __init__(self, name: Optional[Any] = ..., platform: Optional[Any] = ...) -> None: ...
    def isKnown(self): ...
    def getType(self): ...
    def isMacOSX(self): ...
    def isWinNT(self): ...
    def isWindows(self): ...
    def isVista(self): ...
    def isLinux(self): ...
    def isDocker(self, _initCGroupLocation: str = ...): ...
    def supportsThreads(self): ...
    def supportsINotify(self): ...

platform: Any
platformType: Any
seconds: Any
