from typing import Any, Optional

def open(filename: Any): ...

class Shortcut:
    def __init__(self, path: Optional[Any] = ..., arguments: Optional[Any] = ..., description: Optional[Any] = ..., workingdir: Optional[Any] = ..., iconpath: Optional[Any] = ..., iconidx: int = ...) -> None: ...
    def load(self, filename: Any) -> None: ...
    def save(self, filename: Any) -> None: ...
    def __getattr__(self, name: Any): ...
