from twisted.python import log as log
from typing import Any

syslog: Any
DEFAULT_OPTIONS: int
DEFAULT_FACILITY: Any

class SyslogObserver:
    openlog: Any = ...
    syslog: Any = ...
    def __init__(self, prefix: Any, options: Any = ..., facility: Any = ...) -> None: ...
    def emit(self, eventDict: Any) -> None: ...

def startLogging(prefix: str = ..., options: Any = ..., facility: Any = ..., setStdout: int = ...) -> None: ...
