from typing import Any, Optional

class ListenFDs:
    def __init__(self, descriptors: Any) -> None: ...
    @classmethod
    def fromEnvironment(cls, environ: Optional[Any] = ..., start: Optional[Any] = ...): ...
    def inheritedDescriptors(self): ...
