from typing import Any, Iterable, List, Mapping, Optional

class ListenFDs:
    def __init__(self, descriptors: List[int]) -> None: ...
    @classmethod
    def fromEnvironment(cls: Any, environ: Optional[Mapping[str, str]]=..., start: Optional[int]=...) -> ListenFDs: ...
    def inheritedDescriptors(self) -> Iterable[int]: ...
