from typing import Any

def stringyString(object: Any, indentation: str = ...): ...
def isMultiline(s: Any): ...
def endsInNewline(s: Any): ...
def greedyWrap(inString: Any, width: int = ...): ...
wordWrap = greedyWrap

def removeLeadingBlanks(lines: Any): ...
def removeLeadingTrailingBlanks(s: Any): ...
def splitQuoted(s: Any): ...
def strFile(p: Any, f: Any, caseSensitive: bool = ...): ...
