from twisted.python.compat import nativeString as nativeString, unicode as unicode, urlquote as urlquote, urlunquote as urlunquote
from typing import Any

class URLPath:
    def __init__(self, scheme: bytes = ..., netloc: bytes = ..., path: bytes = ..., query: bytes = ..., fragment: bytes = ...) -> None: ...
    scheme: Any = ...
    netloc: Any = ...
    path: Any = ...
    query: Any = ...
    fragment: Any = ...
    def pathList(self, unquote: bool = ..., copy: bool = ...): ...
    @classmethod
    def fromString(klass: Any, url: Any): ...
    @classmethod
    def fromBytes(klass: Any, url: Any): ...
    @classmethod
    def fromRequest(klass: Any, request: Any): ...
    def sibling(self, path: Any, keepQuery: bool = ...): ...
    def child(self, path: Any, keepQuery: bool = ...): ...
    def parent(self, keepQuery: bool = ...): ...
    def here(self, keepQuery: bool = ...): ...
    def click(self, st: Any): ...
