from typing import Any

ERROR_FILE_NOT_FOUND: int
ERROR_PATH_NOT_FOUND: int
ERROR_INVALID_NAME: int
ERROR_DIRECTORY: int
O_BINARY: Any

class FakeWindowsError(OSError): ...
WindowsError = WindowsError
WindowsError = FakeWindowsError

def cmdLineQuote(s: Any): ...
def quoteArguments(arguments: Any): ...

class _ErrorFormatter:
    winError: Any = ...
    formatMessage: Any = ...
    errorTab: Any = ...
    def __init__(self, WinError: Any, FormatMessage: Any, errorTab: Any) -> None: ...
    def fromEnvironment(cls): ...
    fromEnvironment: Any = ...
    def formatError(self, errorcode: Any): ...

formatError: Any
